### ISSUE TITLE
wireshark portable error

### ISSUE THREAD

**Issue by VineetTambe** [telekom/5g-trace-visualizer#11]
I am trying to run the 5g-trace-visualizer:
I have fulfilled all the requirements as stated however whenever I run the following command
```
python trace_visualizer.py -wireshark 3.2.2 "./doc/free5gc.pcap"
```
it throws this error
![error](https://user-images.githubusercontent.com/52542471/97435811-f85a3a80-1946-11eb-820a-ece127fed92a.PNG)
![error-2](https://user-images.githubusercontent.com/52542471/97435815-f98b6780-1946-11eb-8240-a4f7c53f7ae1.PNG)

any help would be appreciated !

**Comment by jkolom** [comment]
Without having more details it is a bit difficult to diagnose, but from the exception, it seems like that script cannot find the ``tshark`` executable.

Since you run it with the option ``-wireshark 3.2.2``, this means that the script checks the ``wireshark`` folder, where you hsould have placed Wireshark Portable into the ``WiresharkPortable_3.2.2`` folder. In your case, that is the ``/home/vineet/.../wireshark/WiresharkPortable_3.2.2/App/Wireshark/tshark``. Since #4, #10, we saw that the scripts should also work for Linux (some minor tweaks were done), so the issue cannot be with the OS.

The recommendation wold be to check:
* Are the Wireshark portable files where they should be? I assume "no"
* You could also try the ``OS`` value for ``wireshark``. As listed in the command help: ``'OS' can be used as version number if you do not want to use a specific Wireshark version but rather the OS-installed Wireshark/tshark version you have within your PATH`` 

I will close the issue. Feel free to reopen it if you think that it is a bug and not a mis-configuration and/or missing file(s).
