### ISSUE TITLE
FileNotFoundError: Could not find tshark on path tshark

### ISSUE THREAD

**Issue by lukedevon** [telekom/5g-trace-visualizer#15]
Hi , 

I tried to start with the sample command you have given in the documentation. 
python3 trace_visualizer.py -wireshark "OS" ./doc/free5gc.pcap

But I got the following message:

DEBUG:root:Preparing call for Wireshark version OS
DEBUG:root:tshark path: tshark
Traceback (most recent call last):
  File "trace_visualizer.py", line 1695, in <module>
    input_file = call_wireshark(args.wireshark, input_file, args.http2ports)
  File "trace_visualizer.py", line 1457, in call_wireshark
    output_file = call_wireshark_for_one_version(wireshark_version, input_file_str, http2ports_string)
  File "trace_visualizer.py", line 1504, in call_wireshark_for_one_version
    raise FileNotFoundError('Could not find tshark on path {0}'.format(tshark_path))
FileNotFoundError: Could not find tshark on path tshark

According to the message, it says that "FileNotFoundError: Could not find tshark on path tshark". But I already have installed tshark , and wirshark.

$ which tshark
/usr/bin/tshark

$ which wireshark
/usr/bin/wireshark

any suggestion please? Can I know what I have done wrong here ?
Also , can I check with you, can we use this script to draw SVG sequence diagrams using 5g http2 traces only for a specific IMSI?

Thanks
Luke.

**Comment by vineet-rarisystems** [comment]
Hey,
Did you copy-paste the correct version of wireshark in this location ```/wireshark```. [see instructions](https://github.com/vineet-rarisystems/5g-trace-visualizer/blob/master/wireshark/Readme.md)

**Comment by lukedevon** [comment]
Hi, 

Thank you for the reply and the support. Let me explain what are the steps that I have followed. Actually I think I have followed your instructions correctly. But let me explain;

1. I downloaded the WiresharkPortable_2.9.0.paf.exe and extracted it .  Then I got the this folder "WiresharkPortable". 
2. I uploaded the whole folder (including its contents) to the wireshark folder of the root directory.
/opt/5g-trace-visualizer/wireshark
* /opt/5g-trace-visualizer/wireshark/WiresharkPortable
executed the command but got the same error message.

3. Then I copied only the content to the wireshark folder
/opt/5g-trace-visualizer/wireshark --> ls
pp  Data  help.html  Other  WiresharkPortable.exe

executed the command but still the same error.

4. Then I copied the entire folder including its content by renaming like this --> WiresharkPortable_2.9.0
* /opt/5g-trace-visualizer/wireshark/WiresharkPortable_2.9.0

ls 
* App  Data  help.html  Other  WiresharkPortable.exe

But still I am getting same error.

May I know, did I miss any step on your instructions ? My OS is ubuntu 20.04 Desktop version.

Thanks
Luke.

**Comment by jkolom** [comment]
Hi,

When setting the wireshark option to ``os``, the script makes a call to ``tshark`` instead of to (example for the case you put ``-wireshark 3.4.1`` to make the string more understandable) ``wireshark/WiresharPortable_3.4.1/App/Wireshark/tshark`` (see code [here](https://github.com/telekom/5g-trace-visualizer/blob/96af014b2f9c11b6b2e80c1d5da7efb8b694f0f4/trace_visualizer.py#L1492)).

A couple of comments/questions:
- Is ``tshark`` in your path? If a normal user cannot run ``tshark`` from any folder, neither will the script. Although I developed this on Windows with Windows in mind, it should work on Linux (at least according to user feedback from #4, #10)
- The Wireshark Portable package you downloaded is for Windows (``exe``), it won't run on Linux

BR,
Josep
