### ISSUE TITLE
docker supported

### ISSUE THREAD

**Issue by herugen** [telekom/5g-trace-visualizer#16]
hi, thanks for sharing this excellent tools. do you have plan package this tool into docker images? its a little hard to prepare the environment without knowledge of java. thanks again

**Comment by jkolom** [comment]
Thanks for the praise 👍 
Unfortunately, I am not planning to package this into docker. A couple of reasons I thought for this decision:

- The target audience implies someone with interest in visualizing the insides of 5GS traces. These are quite complex and implies quite some technical know-how and/or interest in technical details. I would be surprised if such a person cannot install Java and copy a couple of files ;)
- If it would be packaged in a container, it would need to contain (at least) Java, PlantUML and Wireshark. But since there is no server way to communicate with it, you would need to access the container's console to execute the scripts
- Additionally, setup shared folders so that you can access the traces and (e.g.) use other Wireshark versions than the one packaged in the container

All in all, it would be quite some work but I am not sure if it would be a bit cumbersome.

If the issue is that the Java client used is the one in ``PATH``, I could implement (or I would be very grateful if you could do that) an option to add a Java path, that would be no problem at all.
