### ISSUE TITLE
Diameter packet description on SVG

### ISSUE THREAD

**Issue by OrlandoST** [telekom/5g-trace-visualizer#21]
When parameters `-simple_diagrams` is set we don't see informatical diameter packet description:

![image](https://user-images.githubusercontent.com/4140759/145169504-a7b41165-8035-4f59-afd8-a7ff100d84e8.png)

It will be better to extend diameter packet description.  
For example:
![image](https://user-images.githubusercontent.com/4140759/145169157-5f9def65-9137-4fc8-921c-2c83c31e28a0.png)

**Comment by jkolom** [comment]
The easiest way would be to improve the [packet_to_str()](https://github.com/telekom/5g-trace-visualizer/blob/5322c7f98ac1ce9811c94ba253126f3c36be851b/trace_visualizer.py#L727) function to write a better one-liner summarizing the protocol for Diameter messages.

On the first pass, it just write the protocol name, but as you can see for the simple [PFCP case](https://github.com/telekom/5g-trace-visualizer/blob/5322c7f98ac1ce9811c94ba253126f3c36be851b/trace_visualizer.py#L791-L801), it is possible to convert such a line to ``PFCP req.`` or ``PFCP rsp.`` based on the packet contents. Something similar could be done for protocol ``Diameter``,

There is a [small snippet already processing Diameter](https://github.com/telekom/5g-trace-visualizer/blob/5322c7f98ac1ce9811c94ba253126f3c36be851b/trace_visualizer.py#L815-L816), it currently only changes the color of the Diameter messages to yellow. But it could be extended to contain a small summary of the message as you show in your picture.

[NGAP/NAS messages](https://github.com/telekom/5g-trace-visualizer/blob/5322c7f98ac1ce9811c94ba253126f3c36be851b/trace_visualizer.py#L731-L761) needed such an "additional couple of lines" because I needed to include for better clarity the binary (hex) content of the message because some people wanted to compare the binary content compared to the spec IEs.

When activating ``simple_diagrams``, the packet content gets removed and only the ``protocol`` content is shown. In the normal case, both are shown. I anyway, I think that your proposed text is better readable than the original one.

Feel free to to a merge request if you want/find time to :)

**Comment by OrlandoST** [comment]
Feature added in b69e4e6a3a0305ee86fe3b8c4c69a3c17deeda48
